package com.madgaze.watchsdk;

public enum WatchGesture {
    FOREARM_LEFT(1),
    FOREARM_RIGHT(2),
    HANDBACK_UP(3),
    HANDBACK_DOWN(4),
    HANDBACK_LEFT(5),
    HANDBACK_RIGHT(6),
    THUMBTAP_INDEX_MIDDLE(7),
    FINGER_SNAP(8),
    FOREARM_LEFT_2(9),
    FOREARM_RIGHT_2(10),
    HANDBACK_UP_2(11),
    HANDBACK_DOWN_2(12),
    HANDBACK_LEFT_2(13),
    HANDBACK_RIGHT_2(14),
    THUMBTAP_INDEX_MIDDLE_2(15),
    FINGER_SNAP_2(16),
    JOINTTAP_LOWER_THUMB(17),
    JOINTTAP_UPPER_THUMB(18),
    JOINTTAP_MIDDLE_INDEX(19),
    JOINTTAP_UPPER_INDEX(20),
    JOINTTAP_MIDDLE_MIDDLE(21),
    JOINTTAP_UPPER_MIDDLE(22),
    JOINTTAP_MIDDLE_RING(23),
    JOINTTAP_UPPER_RING(24),
    JOINTTAP_MIDDLE_LITTLE(25),
    THUMBTAP_INDEX(26),
    THUMBTAP_MIDDLE(27),
    THUMBTAP_INDEX_2(28),
    THUMBTAP_MIDDLE_2(29),
    MOVE_FOREARM_UP(30),
    MOVE_FOREARM_DOWN(31),
    MOVE_FOREARM_LEFT(32),
    MOVE_FOREARM_RIGHT(33);

    private final int gestureId;
    WatchGesture(int gestureId) {
        this.gestureId = gestureId;
    }
    protected int getGestureId() {
        return gestureId;
    }
}
